---
clusterName: "capt-playground"
outputDir: "output"
namespace: "tink"
counts:
  controlPlanes: 1
  workers: 1
  spares: 1
versions:
  capt: 0.5.3
  chart: 0.5.0
  kube: v1.29.4
  os: 20.04
  kubevip: 0.8.2
os:
  registry: ghcr.io/tinkerbell/cluster-api-provider-tinkerbell
  distro: ubuntu
  sshKey: ""
vm:
  baseName: "node"
  cpusPerVM: 2
  memInMBPerVM: 2048
  diskSizeInGBPerVM: 10
  diskPath: "/tmp"
virtualBMC:
  containerName: "virtualbmc"
  image: ghcr.io/jacobweinstock/virtualbmc
  user: "root"
  pass: "calvin"
